#!/bin/sh
#
# rcS		Call all S??* scripts in /etc/rcS.d in
#		numerical/alphabetical order.
#
# Version:	@(#)/etc/init.d/rcS  2.76  19-Apr-1999  miquels@cistron.nl
#
# set -x
PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#make node for user device
mknod /dev/fpga c 10 223
mknod /dev/ad9363 c 10 224
mknod /dev/davinci_gpio c 10 225
mknod /dev/it66121 c 10 226
mknod /dev/adv7611 c 10 227

#make node for dm368 *.ko

#if [ -x loadmodule-rc ]
#then
#  ./loadmodule-rc start
#fi


#	Make sure proc is mounted
#
[ -d "/proc/1" ] || mount /proc

#
#	See if system needs to be setup. This is ONLY meant to
#	be used for the initial setup after a fresh installation!
#
if [ -x /sbin/unconfigured.sh ]
then
 /sbin/unconfigured.sh
fi


#
#	Source defaults.
#
. /etc/default/rcS

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP

#
#	Call all parts in order.
#
exec /etc/init.d/rc S

#
#	For compatibility, run the files in /etc/rc.boot too.
#
[ -d /etc/rc.boot ] && run-parts /etc/rc.boot

#
#	Finish setup if needed. The comment above about
#	/sbin/unconfigured.sh applies here as well!
#
if [ -x /sbin/setup.sh ]
then
 /sbin/setup.sh
fi



